### ISSUE TITLE
Meta keys mess up the value when predictInputValue is used in onKeyDown

### ISSUE THREAD

**Issue by gilles-yvetot** [wojtekmaj/predict-input-value#3]
When special keys are typed, it messes up the value:
- Enter
- Escape
- Shift
- ArrowUp
- ArrowDown
- ArrowRight
- ArrowLeft
- Alt
- Tab

**Comment by wojtekmaj** [comment]
Thanks for reporting! In onKeyDown that was indeed the case since `metaKey` property in `event` was `false`.

**Comment by wojtekmaj** [comment]
Released in v1.0.1.
